[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "finetuna"
version = "0.1.3"
requires-python = ">=3.10"
dependencies = [
    "accelerate",
    "bitsandbytes==0.42.0",
    "diffusers",
    "einops",
    "evaluate",
    "huggingface",
    "pandas",
    "peft",
    "pyyaml",
    "scikit-learn",
    "torch",
    "tqdm",
    "transformers",
    "trl",
    "wandb",
]

[project.scripts]
finetuna = "finetuna.__main__:main"

[tool]
