name: Publish package to PyPI

on:
  # 当前分支更新时触发
  push:
    branches:
      - test-python-rye

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3
        with:
            version: 'latest'

      - name: python version
        run: rye pin 3.8

      - name: Install dependencies
        run: rye sync

      - name: Build package
        run: rye build

      - name: Twine upgrade
        run: $RYE_HOME/self/bin/pip install twine>=5.1.1

      - name: Publish package
        run: rye publish --token ${{ secrets.PYPI_API_TOKEN }} --yes