[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "apm.crewconnect"
version = "0.0.1"
authors = [
  { name="Hugo Clarke-Wing", email="hugo@clarkewing.com" },
]
description = "A package to interact with the APM CrewConnect API"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/clarkewing/apm.crewconnect"
Issues = "https://github.com/clarkewing/apm.crewconnect/issues"
