[tool.poetry]
name = "lisa-on-cuda"
version = "1.2.4"
description = ""
authors = ["alessandro trinca tornidor <alessandro@trinca.tornidor.com>"]
license = "Apache 2.0"
readme = "README.md"

[metadata]
name = "lisa-on-cuda"
version = "1.2.4"

[tool.poetry.urls]
Source = "https://huggingface.co/spaces/aletrn/lisa-on-cuda/"
Demo = "https://huggingface.co/spaces/aletrn/lisa-on-cuda/"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
einops = "^0.7.0"
fastapi = "^0.110.0"
markdown2 = "^2.4.13"
nh3 = "^0.2.15"
openai = "^1.13.3"
packaging = "^24.0"
peft-patched = "0.9.3"
gradio = "^4.37.2"
pycocotools = "^2.0.7"
scipy = "^1.11.4"
sentencepiece = "^0.2.0"
shortuuid = "^1.0.12"
torch = "^2.2.1"
torchvision = "^0.17.1"
tqdm = "^4.66.2"
transformers-backport = "4.31.2"
uvicorn = "^0.28.0"
opencv-python-headless = "4.8.1.78"
bitsandbytes = "^0.42.0"
numpy = [
    {version = "1.25.2", python = "~3.10"},
    {version = "^1.26", python = "~3.11"}
]

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
