[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"npsam.button_images" = ["*.png"]

[project]
name = "npsam"
version = "1.6"
dependencies = [
    "numba==0.58.1",
    "opencv-python==4.9.0.80",
    "pandas==2.1.4",
    "matplotlib==3.8.2",
    "scikit-image==0.22.0",
    "ipympl==0.9.3",
    "PyQt5==5.15.10",
    "ultralytics==8.1.2",
    "jupyterlab==4.0.10",
    "clip==0.2.0",
    "piexif==1.1.3",
    "hyperspy[all]==2.1.0",
    "parse==1.20.1",
    "h5py==3.10.0",
    "tifffile==2024.1.30"
]


requires-python = ">= 3.10"
authors = [
    {name = "Larsen, R. & Villadsen, T.", email = "rasmus@inano.au.dk"}
]
description="NP-SAM is an easy-to-use segmentation and analysis tool for nanoparticles and more."
readme = "README.md"
license = {file = "LICENSE.txt"}
keywords = ["nanoparticles", "segmentation"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
]
