[project]
name = "bfiola-operator-core"
version = "1.0.0"
dependencies = [ "fastapi", "kopf", "lightkube", "lightkube-models", "pydantic", "uvicorn",]

[project.optional-dependencies]
dev = [ "bfiola-devtools",]

[tool.setuptools.packages.find]
include = [ "operator_core",]
