[project]
name = "test_rye"
version = "0.1.2"
description = "Add your description here"
authors = [{ name = "xiaohuohumax" }]
dependencies = []
license = { text = "MIT" }
homepage = "https://github.com/xiaohuohumax/test"
repository = "https://github.com/xiaohuohumax/test"
documenation = "https://github.com/xiaohuohumax/test"
keywords = ["test", "rye"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/test_rye"]

[tool.rye.scripts]
start = "python -m src.main"
