[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "boxcat"
version = "0.0.2"
authors = [
  { name="Michael Yau", email="m.yw.yau@gmail.com" },
]
description = "small playground library for fp in python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/mywyau/boxcat"
Issues = "https://github.com/mywyau/boxcat/issues"