






[tool.poetry]
name = "Titaness"
version = "2.0.0"
description = "Bringing fame, fortune, and health to friends and family"
authors = []
readme = "venues/stages/Titaness/readme.md"

packages = [
    { include = "Titaness", from = "venues/stages" }
]
exclude = []
include = [ "*.HTML", "*.html", "*.JSON", "*.json" ]

license = "GPL-3.0-only"

keywords = [
	"alarms",
	"screening",
	"monitors",

	"cybernetics",
	"neurons",
	"nervous system",
	"bioelectric",

	"homeostasis",
	"reliability",
	"consistency",
	"integrity",
	
	"guarantees",
	"vows",
	"oaths",
	"assurances",
	"insurances",
	"ensurances",

	"speed",
	"calmness",

	"education",

	"augmentation",
	"enhancement",
	"improvements"
]


[tool.poetry.dependencies]
python = "^3.10"
body-scan = "^1.1.1"
botanist = "^1.0.0"
click = "^8.1.7"
coverage = "^7.4.4"
flask = "^3.0.3"
pexpect = "^4.9.0"
redis = "^5.0.3"
requests = "^2.31.0"
tinydb = "^4.8.0"
rich = "^13.7.1"
sanic = "^23.12.1"
pymongo = "^4.6.3"
mako = "^1.3.3"


[tool.poetry.scripts]
Titaness = 'Titaness:clique'


[tool.poetry.urls]
GitLab = "https://gitlab.com/status600/treasures/Titaness.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"




