[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
authors = ["Michael James Schock <m@mjschock.com>"]
description = ""
license = "MIT"
name = "timestep"
packages = [{from = "src", include = "timestep"}]
readme = "README.md"
version = "10.0.19"

[tool.poetry.dependencies]
openai = "^1.35.10"
python = "^3.10"
typer = {extras = ["all"], version = "^0.12.3"}
ctransformers = "^0.2.27"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
ipywidgets = "^8.1.3"
pytest = "^8.2.2"
toml-sort = "^0.23.1"

[tool.poetry.scripts]
serve_agent = 'timestep.agent:main'
timestep = 'timestep.main:app'
