[tool.poetry]
name = "telempack"
version = "1.2.0"
description = "A package that uses the OpenTelemetry & Datadog API/SDK to obtain traces, logs, & metrics from services."
authors = ["Max Chalitsios <Max_Chalitsios@eogresources.com>"]
license = "eog"
readme = "README.md"
repository = "https://git.eogresources.com/eog/telemetry-py"

[tool.poetry.dependencies]
python = "^3.12"
ddtrace = "^2.9.2"
opentelemetry-sdk = "^1.25.0"
opentelemetry-api = "^1.25.0"
fastapi = "0.111.0"
pydantic = "2.8.2"
annotated-types = "0.7.0"
anyio = "4.4.0"
certifi = "2024.7.4"
click = "8.1.7"
dnspython = "2.6.1"
email-validator = "2.2.0"
fastapi-cli = "0.0.4"
h11 = "0.14.0"
httpcore = "1.0.5"
httptools = "0.6.1"
httpx = "0.27.0"
idna = "3.7"
jinja2 = "3.1.4"
markdown-it-py = "3.0.0"
markupsafe = "2.1.5"
mdurl = "0.1.2"
orjson = "3.10.6"
pydantic-core = "2.20.1"
pygments = "2.18.0"
python-dotenv = "1.0.1"
python-multipart = "0.0.9"
pyyaml = "6.0.1"
rich = "13.7.1"
shellingham = "1.5.4"
sniffio = "1.3.1"
starlette = "0.37.2"
typer = "0.12.3"
typing-extensions = "4.12.2"
ujson = "5.10.0"
uvicorn = "0.30.1"
uvloop = "0.19.0"
watchfiles = "0.22.0"
websockets = "12.0"
opentelemetry-instrumentation-pymongo = "^0.46b0"
opentelemetry-distro = "^0.46b0"
opentelemetry-instrumentation-sqlalchemy = "^0.46b0"
opentelemetry-instrumentation-psycopg2 = "^0.46b0"
opentelemetry-instrumentation-requests = "^0.46b0"
opentelemetry-instrumentation-starlette = "^0.46b0"
opentelemetry-instrumentation-redis = "^0.46b0"
opentelemetry-instrumentation-asgi = "^0.46b0"
opentelemetry-instrumentation-confluent-kafka = "^0.46b0"
opentelemetry-instrumentation-asyncio = "^0.46b0"
opentelemetry-instrumentation-sqlite3 = "^0.46b0"
opentelemetry-instrumentation-urllib3 = "^0.46b0"
opentelemetry-instrumentation-wsgi = "^0.46b0"
opentelemetry-instrumentation-threading = "^0.46b0"
opentelemetry-instrumentation-kafka-python = "^0.46b0"
opentelemetry-instrumentation-aio-pika = "^0.46b0"
opentelemetry-instrumentation-mysql = "^0.46b0"
opentelemetry-instrumentation-mysqlclient = "^0.46b0"
opentelemetry-instrumentation-psycopg = "^0.46b0"
opentelemetry-instrumentation-pymemcache = "^0.46b0"
opentelemetry-instrumentation-pymysql = "^0.46b0"
opentelemetry-instrumentation-system-metrics = "^0.46b0"
flask = "^3.0.3"

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
