[tool.poetry]
name = "what2"
version = "0.3.1"
description = ""
authors = ["Marc"]
readme = "README.md"
packages = [{include = "what2", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
