[project]
name = "basic-text-effects-biomass2857"
version = "0.0.3"
authors = [
  { name="Tom Reinhardt", email="tomreinhardt3120@gmail.com" },
]
description = "basic text effects"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Biomass2857/basic-text-effects"
Issues = "https://github.com/Biomass2857/basic-text-effects/issues"