[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ihy"
version = "0.0.1"
description = "A Python interface for the Fujin music tag library"
readme = "README.rst"
requires-python = ">=3.11"
license = {file = "LICENSE"}
authors = [
    {name = "James Calo", email = "jamesafcalo@gmail.com"},
]

classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
]

# [project.scripts]
# fujin-edit = "fujin.cli.edit:main"

# [tool.setuptools.packages.find]
# include = [""]

[tool.black]
preview = true
