[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "SpeechCraft"
version = "0.0.0"
description = "Create natural sounding audio from text, clone voices and use them. Convert voice to voice. Bark model."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "SocAIty" }
]
# Apache 2.0
license = {file = "LICENSE"}

dependencies = [
    "media-toolkit[AudioFile]",
    "encodec",
    "fairseq",
    "boto3",
    "funcy",
    "huggingface-hub>=0.14.1",
    "numpy",
    "scipy",
    "tokenizers",
    "torch",
    "tqdm",
    "transformers"
]

[project.urls]
source = "https://github.com/SocAIty/SpeechCraft"

[project.optional-dependencies]
full = [
    "fast-task-api>=0.0.1"
]

[tool.setuptools]
packages = ["speechcraft"]

[tool.setuptools.package-data]
bark = ["assets/prompts/*.npz", "assets/prompts/v2/*.npz"]


[tool.black]
line-length = 100
