[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chaski"
version = "0.1a2"
description = "Chaski Confluence"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "BSD-2-Clause" }
authors = [
    { name = "Yeison Cardona", email = "yencardonaal@unal.edu.co" }
]
maintainers = [
    { name = "Yeison Cardona", email = "yencardonaal@unal.edu.co" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.10",
]
dependencies = []

[project.urls]
"Download" = "https://github.com/dunderlab/python-chaski"

[tool.setuptools.packages.find]
where = ["."]
include = ["chaski"]

[project.optional-dependencies]
dev = [
    "networkx",
    "matplotlib"
    ]
docs = []
