[tool.poetry]
name = "yamlgenerator-hook-search"
version = "1.0.2a"
description = ""
authors = ["kaixinol <keiplyer@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "yamlgenerator_hook_search"}]

[tool.poetry.dependencies]
python = "^3.11"
gameyamlspiderandgenerator = ">=2.0.1a, <3.0"
epicstore-api = "^0.1.6"
serpapi = "^0.1.5"
google-search-results = "^2.4.2"

[tool.poetry.group.dev.dependencies]
epicstore-api = "^0.1.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
