[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sf-utils"
version = "0.0.3"
dependencies = ["fire"]
authors = [
  { name="Aditya Raj", email="aditya2400raj@gmail.com" },
]
description = "Various utilities built around sf-cli"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/aditya24raj/sf_utils"
Issues = "https://github.com/aditya24raj/sf_utils/issues"

[project.scripts]
sf-utils = "sf_utils.sf_utils:__sf_utils__"
